name: Windows Build with ccache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python (required for Meson)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: python -m pip install meson==1.5.0 ninja

    # Step 4: Set up ccache
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        cache-key: ${{ runner.os }}-ccache
        cache-dependency-path: builddir/meson-private/coredata.dat

    # Step 5: Configure Project
    - name: Configure Project
      run: |
        meson setup builddir/ -Dbuildtype=release -Dstrip=true -Ddebug=false

    # Step 6: Build Project
    - name: Build Project
      run: meson compile -C builddir

    # Step 7: Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: okesl-config-ui-build
        path: builddir/