name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python (required for Meson)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: python -m pip install meson==1.5.0 ninja
    - name: Meson WrapDB
      run: meson wrap update-db
    - name: Configure Project
      run: meson setup builddir/ -Dbuildtype=release
    - name: Build meson
      run: ninja -C builddir/ -v

    # Step 6: Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: okesl-config-ui-build
        path: builddir/